[package]
# TODO(1) fix `authors` and `name` if you didn't use `cargo-generate`
authors = ["David Goodlad <david@goodlad.net>"]
name = "crabdac"
edition = "2018"
version = "0.1.0"

[workspace]
members = ["testsuite"]

[dependencies]
cortex-m = "0.7.3"
cortex-m-rt = "0.7.1"
defmt = "0.3.0"
defmt-rtt = "0.3.0"
panic-probe = { version = "0.3.0", features = ["print-defmt"] }
cortex-m-rtic = "0.6.0-rc.4"
stm32f4xx-hal = { version = "0.10.1", features = ["stm32f446", "rtic", "i2s", "usb_fs"] }
stm32_i2s_v12x = "0.2.0"
usb-device = "0.2.8"
heapless = "0.7.9"
as-slice = "0.2.1"
embedded-dma = "0.1.2"
bbqueue = "0.5.1"
stable_deref_trait = { version = "1.2.0", default-features = false }
bytemuck = "1.7.3"

[patch.crates-io]
# Support isochronous endpoints
usb-device = { path = "../usb-device" }
# Support isochronous endpoints
synopsys-usb-otg = { path = "../synopsys-usb-otg" }
# Support ITM1_RMP in TIM2_OR
stm32f4 = { path = "../../stm32-rs/stm32f4" }
# Pull in some recent support for newer cortex-m-rt versions
stm32f4xx-hal = { git = "https://github.com/stm32-rs/stm32f4xx-hal" }
# Fix linker script issues
stm32_i2s_v12x = { git = "https://github.com/samcrow/stm32_i2s" }

[features]
# set logging levels here
default = [
  "defmt-default",
  # "dependency-a/defmt-trace",
]

# do NOT modify these features
defmt-default = []
defmt-trace = []
defmt-debug = []
defmt-info = []
defmt-warn = []
defmt-error = []

# cargo build/run
[profile.dev]
codegen-units = 1
debug = 2
debug-assertions = true # <-
incremental = false
opt-level = "s" # <-
overflow-checks = true # <-

# cargo test
[profile.test]
codegen-units = 1
debug = 2
debug-assertions = true # <-
incremental = false
opt-level = "s" # <-
overflow-checks = true # <-

# cargo build/run --release
[profile.release]
codegen-units = 1
debug = 2
debug-assertions = false # <-
incremental = false
lto = 'fat'
opt-level = "s" # <-
overflow-checks = false # <-

# cargo test --release
[profile.bench]
codegen-units = 1
debug = 2
debug-assertions = false # <-
incremental = false
lto = 'fat'
opt-level = "s" # <-
overflow-checks = false # <-

# uncomment this to switch from the crates.io version of defmt to its git version
# check app-template's README for instructions
# [patch.crates-io]
# defmt = { git = "https://github.com/knurling-rs/defmt", rev = "use defmt version reported by `probe-run --version`" }
# defmt-rtt = { git = "https://github.com/knurling-rs/defmt", rev = "use defmt version reported by `probe-run --version`" }
# defmt-test = { git = "https://github.com/knurling-rs/defmt", rev = "use defmt version reported by `probe-run --version`" }
# panic-probe = { git = "https://github.com/knurling-rs/defmt", rev = "use defmt version reported by `probe-run --version`" }
