name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Install latest nightly
      uses: actions-rs/toolchain@v1
      with:
          toolchain: stable
          override: true
          target: thumbv7em-none-eabi
          components: rustfmt, clippy, llvm-tools-preview
    
    - name: Build
      run: cargo build --release --verbose

    - name: Size
      run: cargo size --release
